// The app icon is the product's own output: key-renderer.ts draws the face,
// this script scales it 144 -> 256, adds the tile's corner radius and rim, and
// writes assets/marketplace.svg plus every raster the manifest and the
// Marketplace listing need.
//
// It used to be the other way round: the SVG was hand-authored with a comment
// asking whoever changed the renderer to change the icon too. Nobody did, and
// by 1.5.0.0 it had drifted five ways (label 22% small, unit 12% small and
// 7px low, sparkline 15% thin and 11px low) across four renderer commits
// between 2026-07-16 and 2026-07-29. Generating it removes the class of bug.
//
// Two deliberate departures from a default key, both about reading as a mark
// rather than as a screenshot:
//   - Type accents off, so the line is Void's own blue. With accents on a
//     temperature draws #FF7E8E, and a pink line in a browse list reads as an
//     alert state rather than as the product.
//   - A fixed history, so the icon is stable across builds.
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

import { renderReadingKey, sparklinePoints, sparklineSvg } from "../src/ui/key-renderer";
import { loadThemes, resolvePalette } from "../src/ui/themes";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const svgPath = path.join(repoRoot, "assets", "marketplace.svg");
const outDir = path.join(repoRoot, "com.lawrensen.hwinfo.sdPlugin", "imgs", "plugin");

const SIZE = 256;
const RADIUS = 52;
const RIM = "#1E242E";

// Values, not coordinates. The renderer min/max-normalizes them into whatever
// band it currently uses, so this line keeps its shape (the rising walk the
// icon has had since 1.1.8) wherever the band moves next.
const HISTORY = [5.5, 9.7, 6.9, 14.0, 10.3, 16.8, 12.6, 18.8, 15.4, 22.5, 18.8, 24.5, 28.2];

const palette = resolvePalette(loadThemes(), "void", null, "normal");
const face = renderReadingKey({
	label: "CPU",
	valueText: "62",
	unitText: "°C",
	statBadge: "",
	history: HISTORY,
	palette
});

// The renderer insets the sparkline 8 px at each end so its stroke lands
// inside the band. On a key that reads as breathing room; on a tile with a
// 52 px corner radius the right-hand inset shows as a notch of bare
// background between the end dot and the edge, because the line is at its
// highest there and the corner has not started cutting in yet.
//
// So the icon runs the TRACK FILL to both edges while the line and the end
// dot stay exactly where the renderer puts them. The fill is built from the
// line's own points with a flat run added at each end, so its top edge still
// follows the line exactly; stretching the fill instead would slide its peaks
// out of step with the stroke above it.
//
// The same notch exists on a real key. Fixing it there means moving SPARK in
// key-renderer.ts, which moves every rendered key and every golden fixture,
// so it is logged as its own change rather than smuggled in with an icon.
const SPARK = { x: 8, y: 122, w: 128, h: 12 };
const BOTTOM = SPARK.y + SPARK.h;
const points = sparklinePoints(HISTORY, SPARK.x, SPARK.y, SPARK.w, SPARK.h);
const bled = [{ px: 0, py: points[0].py }, ...points, { px: 144, py: points[points.length - 1].py }];
const [, lineSvg, dotSvg] = sparklineSvg(points, BOTTOM, 4, 5, palette);
const [fillSvg] = sparklineSvg(bled, BOTTOM, 4, 5, palette);

const cut = face.indexOf('<path d="M');
if (cut < 0 || face.indexOf("<path", cut + 1) !== -1) {
	throw new Error("gen-icons: expected exactly one <path> (the sparkline track) in the rendered face");
}
const inner = `${face.slice(0, cut)}${fillSvg}${lineSvg}${dotSvg}`.replace(/^<svg[^>]*>/, "");
const scale = SIZE / 144;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}">
	<!-- Generated by scripts/gen-icons.mjs from src/ui/key-renderer.ts. Do not
	     hand-edit: run \`npm run icons\` after any renderer change. -->
	<defs><clipPath id="tile"><rect width="${SIZE}" height="${SIZE}" rx="${RADIUS}"/></clipPath></defs>
	<!-- clip and transform on separate groups: a clipPath resolves in the user
	     space of the element that references it, so a scale on the same element
	     scales the clip rect too and the corners stop being cut. -->
	<g clip-path="url(#tile)"><g transform="scale(${scale})">${inner}</g></g>
	<rect x="1.25" y="1.25" width="${SIZE - 2.5}" height="${SIZE - 2.5}" rx="${RADIUS - 1.25}" fill="none" stroke="${RIM}" stroke-width="2.5"/>
</svg>
`;
writeFileSync(svgPath, svg);

// Max zlib effort: same pixels, ~18% smaller files, and these two PNGs are
// among the largest items in the pack after plugin.js and hwsm.node. Palette
// quantization would halve them again but visibly fringes the icon's
// anti-aliased edges; adaptive filtering also measured larger. Level 9 alone
// is the only encode that shrinks the files with byte-identical pixels.
const png = { compressionLevel: 9 };
const raster = (size, file) => sharp(svgPath, { density: 300 }).resize(size, size).png(png).toFile(file);

// The manifest's top-level Icon must be PNG (256 px + 512 px @2x); every other
// image ships as a single SVG. app-icon-288.png is the Marketplace listing's
// own icon field, checked at 288x288 by scripts/validate-release-copy.mjs.
await raster(256, path.join(outDir, "marketplace.png"));
await raster(512, path.join(outDir, "marketplace@2x.png"));
await raster(288, path.join(repoRoot, "marketing", "app-icon-288.png"));
console.log("Rendered assets/marketplace.svg, marketplace.png (256), marketplace@2x.png (512), app-icon-288.png");
